### ISSUE TITLE
Library File

### ISSUE THREAD

**Issue by fedefiorini** [KioxiaAmerica/SoftwareEnabledFlash#1]
Dears, 
I'm Federico Fiorini, MSc Embedded System student at Delft University of Technology.
I'm currently working on my MSc Thesis on hybrid memory architectures, and I was looking at your Software Enabled Flash with keen interest! 
I was hoping to use the API on GitHub to perform some experiments in implementing some nice functionalities on a Flash device, and I noticed it requires the SEF Hardware Unit and the API implementation, contained in libsef.a.
I hope it would be possible to have access to both of them, in order to complete my research!

**Comment by efp3-kioxia** [comment]
Thanks for your interest in SEF!

We expect samples sometime around the middle of next year.  I fear that timeframe might be out of your MSc Thesis window.

I think the best way would to be ping us here in mid-2021 if you're still looking for access and then we can see what we can do offline to get you access.

Good luck on the research, and thanks again!
